### ISSUE TITLE
Nedi docker can't access mysql

### ISSUE THREAD

**Issue by Tarik-H** [klinnex/nedi#4]
Hi team,
I can't get this compose file to run, I get the error:
> Warning: mysqli_connect(): (HY000/1045): Access denied for user 'root'@'192.168.32.3' (using password: YES) in /var/local/nedi/html/inc/libdb-mysql.php on line 9
> Could not connect to nedi@mysql with root
```
version: '2'
services:
  network-mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=Password-Mysql
    restart: always
    volumes:
      - /docker/mysql:/var/lib/mysql
  nedi:
    depends_on:
      - network-mysql
    image: klinnex/nedi
    environment:
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=Password-Mysql
    links:
      - network-mysql:mysql
    volumes:
      - /docker/nedi:/var/nedi
    ports:
      - "80:80"
      - "514:514"
```
From the mysql container I tested mysql login with root/Password-Mysql and similarly from the Nedi container :
```
root@f2526e1d8544:/var/local/nedi# mysql -h mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.6.45 MySQL Community Server (GPL)
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MySQL [(none)]> 
```
however the nedi DB script doesn't work:

```
root@f2526e1d8544:/var/local/nedi# ./nedi.pl   
DBI connect('dbname=nedi;host=mysql','root',...) failed: Access denied for user 'root'@'192.168.32.3' (using password: YES) at ./inc/libdb.pm line 38.
root@f2526e1d8544:/var/local/nedi# ./nedi.pl -i
Initialize NeDi DB!!!
------------------------------------------------------------------------
mysql admin user: root
mysql admin pass: Password-Mysql
NeDi host (where the discovery runs on: mysql
DB Version      : 5.6.45
----------------------------------------------------------------------
Old DB 'nedi' dropped!
Creating 'nedi' for root@mysql:
DBI connect('dbname=nedi;host=mysql','root',...) failed: Access denied for user 'root'@'192.168.32.3' (using password: YES) at ./inc/libdb.pm line 38.
```
